version: '3.8'

services:
  book_catalog:
    build: ./book_catalog
    platform: linux/amd64
    container_name: book_catalog
    environment:
      DATABASE_URL: "postgresql://eisenlai68_7k9r_user:8xtlWTjTGIzHcIlTKV5cZDA5gDsvR2vF@dpg-crpan768ii6s73cepscg-a.oregon-postgres.render.com/eisenlai68_7k9r"

  inventory_management:
    build: ./inventory_management
    platform: linux/amd64
    container_name: inventory_management
    environment:
      DATABASE_URL: "postgresql://eisenlai68_7k9r_user:8xtlWTjTGIzHcIlTKV5cZDA5gDsvR2vF@dpg-crpan768ii6s73cepscg-a.oregon-postgres.render.com/eisenlai68_7k9r"